# Right leg

r_hip_yaw_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: r_hip_yaw_joint
    max_velocity: 3.0
    motors:
        - id: 1
          init: 512
          min: 0
          max: 1023

r_hip_roll_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: r_hip_roll_joint
    max_velocity: 3.0
    motors:
        - id: 2
          init: 512
          min: 0
          max: 1023

r_hip_pitch_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: r_hip_pitch_joint
    max_velocity: 3.0
    motors:
        - id: 3
          init: 512
          min: 0
          max: 1023

r_knee_pitch_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: r_knee_pitch_joint
    max_velocity: 3.0
    motors:
        - id: 4
          init: 512
          min: 0
          max: 1023

r_ankle_pitch_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: r_ankle_pitch_joint
    max_velocity: 5.0
    motors:
        - id: 5
          init: 512
          min: 0
          max: 1023

r_ankle_roll_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: r_ankle_roll_joint
    max_velocity: 5.0
    motors:
        - id: 6
          init: 512
          min: 0
          max: 1023

# Left leg

l_hip_yaw_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: l_hip_yaw_joint
    max_velocity: 3.0
    motors:
        - id: 7
          init: 512
          min: 0
          max: 1023

l_hip_roll_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: l_hip_roll_joint
    max_velocity: 3.0
    motors:
        - id: 8
          init: 512
          min: 0
          max: 1023

l_hip_pitch_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: l_hip_pitch_joint
    max_velocity: 3.0
    motors:
        - id: 9
          init: 512
          min: 0
          max: 1023

l_knee_pitch_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: l_knee_pitch_joint
    max_velocity: 3.0
    motors:
        - id: 10
          init: 512
          min: 0
          max: 1023

l_ankle_pitch_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: l_ankle_pitch_joint
    max_velocity: 5.0
    motors:
        - id: 11
          init: 512
          min: 0
          max: 1023

l_ankle_roll_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: l_ankle_roll_joint
    max_velocity: 5.0
    motors:
        - id: 12
          init: 512
          min: 0
          max: 1023